source <(antibody init)

# Enable fancy command prompts
setopt prompt_subst

# Enable VI mode line editing 
bindkey -v
zstyle ':completion:*' menu select

# GPG agent configuration
if [ "$(uname -s)" = "Darwin" ]; then
	source ~/.gpg-agent-info
fi

# Use neo vim as the prefered editor
export EDITOR=nvim
alias vi=nvim
alias vim=nvim

# Do not keep command starting with a space in history
setopt histignorespace

# Key bindings
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
bindkey '^R' history-incremental-pattern-search-backward

# Reduce to 0.1s to take into account space key
export KEYTIMEOUT=1

# Go setup
export GOPATH=$HOME/go

# Path
export PATH=$GOPATH/bin:$GOROOT/bin:$HOME/bin:$PATH

# ZSH local variables
if [ -f $HOME/.zshlocal ]; then
  source $HOME/.zshlocal
fi

# Use hub as a git alias if installed
if [ -x "$(which hub)" ]; then
	alias git=hub
fi

# 

# Load antigen
case $(uname -s) in
	Darwin)
		 source /usr/local/share/antigen/antigen.zsh
		;;
	*)
		source /usr/share/zsh-antigen/antigen.zsh
		;;
esac

antigen theme bhilburn/powerlevel9k
# Theme configuration
#export ALIEN_THEME="red"
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs kubecontext newline vi_mode context)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time battery)
POWERLEVEL9K_KUBECONTEXT_BACKGROUND=021
POWERLEVEL9K_VI_INSERT_MODE_STRING="I"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="N"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=5

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions

antigen bundle vi-mode
antigen bundle kubectl
antigen bundle golang
antigen bundle terraform
antigen bundle vault
antigen bundle consul
antigen bundle docker
antigen bundle git
antigen bundle screen

case $(uname -s) in
	Darwin)
		antigen bundle kubectl
		;;
esac

antigen apply

# Enable completion
autoload -Uz compinit
compinit

# Terraform
if [ -d $HOME/.tfenv/bin ]; then
  export PATH=$HOME/.tfenv/bin:$PATH
fi

# RVM
if [ -f $HOME/.rvm/scripts/rvm ]; then
  source $HOME/.rvm/scripts/rvm
fi

# SDK man
if [ -d "$HOME/.sdkman" ]; then
	export SDKMAN_DIR="$HOME/.sdkman"
	if [ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]; then
		source "$SDKMAN_DIR/bin/sdkman-init.sh"
	fi
fi
