# Enable fancy command prompts
#setopt prompt_subst

# Enable VI mode line editing
bindkey -v

# GPG agent configuration
if [ -S "$HOME/.gnupg/S.gpg-agent.ssh" ]; then
	export SSH_AUTH_SOCK="$HOME/.gnupg/S.gpg-agent.ssh"
elif [ -S "$XDG_RUNTIME_DIR/gnupg/S.gpg-agent.ssh" ]; then
	export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gnupg/S.gpg-agent.ssh"
fi

# Use neo vim as the prefered editor
export EDITOR=nvim
alias vi=nvim
alias vim=nvim

# Key bindings
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey '^R' history-incremental-pattern-search-backward
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^[[3~' delete-char
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# Reduce to 0.1s to take into account space key
export KEYTIMEOUT=1

# Go setup
export GOPATH=$HOME/go

# Path
path+=($GOPATH/bin $GOROOT/bin $HOME/local/bin $HOME/bin)

# Cargo
if [ -d "$HOME/.cargo/bin" ]; then
    path+="$HOME/.cargo/bin"
fi

# Snap
if [ -d /snap/bin ]; then
  path+=/snap/bin
fi

# Terraform
if [ -d $HOME/.tfenv/bin ]; then
    path+=$HOME/.tfenv/bin
fi

# ZSH local variables
if [ -f $HOME/.zshlocal ]; then
  source $HOME/.zshlocal
fi

# Use hub as a git alias if installed
if [ -x "$(which hub)" ]; then
	alias git=hub
fi


# Enable completion
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select

# Theme configuration
VI_MODE_RPROMPT_DISABLED=true
#POWERLEVEL9K_MODE='nerdfont-complete'
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs kubecontext newline vi_mode context)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time battery)
#POWERLEVEL9K_DIR_HOME_BACKGROUND="cyan"
#POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="cyan"
#POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="cyan"
#POWERLEVEL9K_KUBECONTEXT_BACKGROUND="blue"
#POWERLEVEL9K_KUBECONTEXT_FOREGROUND="white"
#POWERLEVEL9K_VI_INSERT_MODE_STRING="I"
#POWERLEVEL9K_VI_COMMAND_MODE_STRING="N"
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=5
if [ -f ~/.zshcolor ]; then
	source ~/.zshcolor
fi

# Load zplug
source ~/.zplug/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

#zplug "bhilburn/powerlevel9k", as:theme

zplug "lib/history",   from:oh-my-zsh

zplug "plugins/history",   from:oh-my-zsh
zplug "gjacquet/ohmyzsh",  use:"plugins/vi-mode"
zplug "plugins/kubectl",   from:oh-my-zsh
zplug "plugins/golang",    from:oh-my-zsh
zplug "plugins/terraform", from:oh-my-zsh
zplug "plugins/vault",     from:oh-my-zsh
zplug "plugins/consul",    from:oh-my-zsh
zplug "plugins/docker",    from:oh-my-zsh
zplug "plugins/git",       from:oh-my-zsh
zplug "plugins/github",    from:oh-my-zsh
zplug "plugins/screen",    from:oh-my-zsh
zplug "plugins/brew",      from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"

zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-autosuggestions"

if typeset -f zsh_load_local_plugins > /dev/null; then
  zsh_load_local_plugins
fi

if ! zplug check; then
    zplug install
fi
zplug load

# RVM
if [ -f $HOME/.rvm/scripts/rvm ]; then
  source $HOME/.rvm/scripts/rvm
fi

function switch-color-scheme {
	color="$1"

	echo "export POWERLEVEL9K_COLOR_SCHEME=\"$color\"" > "$HOME/.zshcolor"

	rm -f "$HOME/.config/nvim/color.nvim"
	ln -s "$HOME/.config/nvim/color-$color.nvim" "$HOME/.config/nvim/color.nvim"

	if [ -d "$HOME/.config/kitty/" ]; then
		rm -f "$HOME/.config/kitty/kitty-colors.conf"
		ln -s "$HOME/.config/kitty/kitty-solarized-$color.conf" "$HOME/.config/kitty/kitty-colors.conf"
    fi
	if [ -d "$HOME/Library/Preferences/kitty/" ]; then
		rm -f "$HOME/Library/Preferences/kitty/kitty-colors.conf"
		ln -s "$HOME/Library/Preferences/kitty/kitty-solarized-$color.conf" "$HOME/Library/Preferences/kitty/kitty-colors.conf"
    fi
}

function use-light-color-scheme {
	switch-color-scheme "light"
}

function use-dark-color-scheme {
	switch-color-scheme "dark"
}

eval "$(starship init zsh)"

# SDK man
if [ -d "$HOME/.sdkman" ]; then
	export SDKMAN_DIR="$HOME/.sdkman"
	if [ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]; then
		source "$SDKMAN_DIR/bin/sdkman-init.sh"
	fi
fi
