export OPERATING_SYSTEM_NAME=`uname -s`

case $OPERATING_SYSTEM_NAME in
	"Darwin")
		source $HOME/.bash_scripts/macos
		;;
esac

source $HOME/.bash_scripts/git_completion
source $HOME/.bash_scripts/java
source $HOME/.bash_scripts/maven
source $HOME/.bash_scripts/grails
source $HOME/.bash_scripts/alias

export PS1="\\w : \$(git branch 2>/dev/null | grep '^*' | colrm 1 2)\$ "

